FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    wget git zip unzip libicu-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-install intl opcache pdo pdo_mysql mbstring zip


COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer


WORKDIR /var/www/html


RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf


RUN a2enmod rewrite


COPY ./ /var/www/html/


RUN chown -R www-data:www-data /var/www/html


RUN composer install --optimize-autoloader


EXPOSE 80
